services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_DB: foxchess
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Bn054Vb007@
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  e1-foxchess:
    build:
      dockerfile: Dockerfile
    container_name: e1-foxchess
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - foxchess-logs:/app/src/logs
    networks:
      - foxchess-network
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: Bn054Vb007@
      DB_NAME: foxchess

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
    networks:
      - foxchess-network
    depends_on:
      - e1-foxchess
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-lifecycle
  
  grafana:
    build:
      context: ./monitoring/grafana
      dockerfile: Dockerfile
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - foxchess-network
    depends_on:
      - prometheus
    volumes:
      - grafana-storage:/var/lib/grafana
      - .monitoring/grafana/provisioning:/etc/grafana/provisioning

networks:
  foxchess-network:

volumes:
  grafana-storage:
  foxchess-logs:
  postgres_data:
